CREATE TABLE PROFESSOR (
    ID INT UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50),
    SUBJECT_ID INT,
    CONSTRAINT PK_PROFESSOR PRIMARY KEY (ID)

);

CREATE TABLE SUBJECT (
    ID INT UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    YEAR CHAR(4) NOT NULL,
    PROFESSOR_ID INT,
    STUDENT_ID INT,
    CONSTRAINT PK_SUBJECT PRIMARY KEY (ID)

);

CREATE TABLE STUDENT (
    ID INT UNIQUE,
    INDEX CHAR(6) NOT NULL,
    EMAIL CHAR(4) NOT NULL,
    SUBJECT_ID INT,
    CONSTRAINT PK_STUDENT PRIMARY KEY (ID)
);

CREATE TABLE SESSION (
    ID INT UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    DUE_DATE DATE NOT NULL,
    SUBJECT_ID INT,
    CONSTRAINT PK_SESSION PRIMARY KEY (ID)

);

CREATE TABLE RESULTS (
    ID INT UNIQUE,
    SUBJECT_ID INT NOT NULL,
    SESSION_ID INT,
    LINK_PDF VARCHAR(255),
    CONSTRAINT PK_RESULTS PRIMARY KEY (ID)


);

ALTER TABLE PROFESSOR
    ADD CONSTRAINT FK_SUBJECT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT(ID);

ALTER TABLE SUBJECT
    ADD CONSTRAINT FK_PROFESSOR FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR(ID),
    ADD CONSTRAINT FK_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID);

ALTER TABLE STUDENT
    ADD CONSTRAINT FK_SUBJECT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT(ID);

ALTER TABLE SESSION
    ADD CONSTRAINT FK_SUBJECT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT(ID);

ALTER TABLE RESULTS
    ADD CONSTRAINT FK_SUBJECT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT(ID),
    ADD CONSTRAINT FK_SESSION FOREIGN KEY (SESSION_ID) REFERENCES SESSION(ID);