version: "3"
services:
  app-db:
    image: "postgres"
    restart: always
    container_name: "results_management_container"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=results-publishing-db
    ports:
      - "5432:5432"
    volumes:
      - init:/var/lib/postgresql/data
  backend:
    depends_on:
      - app-db
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: results_management_backend
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://app-db:5432/results-publishing-db"
volumes:
  init:
